---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=T}
Sys.setenv(TZ = 'UTC')

library(motus)
library(tidyverse)
library(data.table)
library(leaflet)
library(lubridate)

# load helper function, a time-saving collection of functions I often use
source('./helper_functions.R')

# log into motus
motus_login()

# define data directory
if (file.exists('//tsclient/D/')) {
  dd <- 'C:/MotusData/'
} else
  dd <- remoted('D:/MotusData/')

# rds directory
outdir <- remoted('D:/OneDrive/R/StationSummary/')

# data to download
d <- 'SG-3214BBBK5757'

```

```{r download data or connect to local .motus file}


# path to local .motus file (if one exists)
# this just makes it quicker to check whether there is a .motus file
# regardless of the kind of data being downloaded
dbpath <- paste0(dd,
                 ifelse(grepl('CTT|SG|Lotek', d), d, paste0('Project-', d)),
                 '.motus')

# download the data
m <- tagme(
  projRecv = d,
  new = !file.exists(dbpath),
  update = T,
  forceMeta = T,
  dir = dd
)

# update metadata system wide explicitly
# metadata(m)
```

```{r create and save allruns table}
create_allruns(m)

# create allruns and modify timestamps
allruns <- tbl(m, 'allruns') %>%
  as.data.table() %>%
  mutate(
    tsBeginCorrected = as.POSIXct(tsBeginCorrected, tz = 'UTC', origin = '1970-01-01'),
    tsEndCorrected = as.POSIXct(tsEndCorrected, tz = 'UTC', origin = '1970-01-01')
  )

# Save allruns as RDS locally
saveRDS(allruns,
        file = paste0(
          outdir,
          'allruns_',
          ifelse(grepl('CTT|SG|Lotek', d), d, paste0('Project-', d)),
          '_',
          Sys.Date(),
          '.RDS'
        ))
```

```{r load allruns from file}
# loads the most recent all runs RDS file in the outdir directory (if one exists)
allruns_rdsfile <- max(gtools::mixedsort(list.files(
  outdir,
  pattern = paste0('allruns_',
                   ifelse(
                     grepl('CTT|SG|Lotek', d), d, paste0('Project-', d)
                   )),
  full.names = T
)))

if (file.exists(allruns_rdsfile)) {
  allruns <- read_rds(allruns_rdsfile)
} else
  message('allruns RDS file does not exist')

# summarize runs with runLen > 3
goodruns_summary <- allruns %>%
  filter(runLen > 3) %>%
  summarize_runs()                                            
```

```{r create and save alltags}
# create alltags
alltags <- tbl(m, 'alltags') %>%
  as.data.table() %>%
  mutate(tsCorrected = as.POSIXct(tsCorrected, tz = 'UTC', origin = '1970-01-01'))

# save alltags as RDS
saveRDS(alltags,
        file = paste0(
          outdir,
          'alltags_',
          ifelse(grepl('CTT|SG|Lotek', d), d, paste0('Project-', d)),
          '_',
          Sys.Date(),
          '.RDS'
        ))

```

```{r load alltags file and summarize}
alltags_rdsfile <- max(gtools::mixedsort(list.files(
  outdir,
  pattern = paste0('alltags_',
                   ifelse(
                     grepl('CTT|SG|Lotek', d), d, paste0('Project-', d)
                   )),
  full.names = T
)))


if (file.exists(alltags_rdsfile)) {
  alltags <- read_rds(alltags_rdsfile)
} else
  message('alltags RDS file does not exist')


# summarize runs with runLen > 3
goodhits_summary <- alltags %>%
  filter(runLen > 3) %>%
  summarize_hits()


```

```{r plot daily pulse counts}
# all_pulses <- pulse_summary(d)[['pulse_summary']]
# pulses_by_day <- pulse_summary(d)[['daily_pulse_summary']]
# 
# pulses_by_day  %>%
#   filter(date > '2010-01-01', ant == 0)%>% 
#   ggplot() +
#   geom_point(aes(date, daily_pulses)) +
#   scale_x_date(date_labels = "%Y-%m-%d") +
#   scale_y_continuous(labels = scales::comma)




library(dplyr)
library(DBI)

# connect to db
db <- connect_to_db()

# receiver to summarize (Tadoussac)
# https://motus.org/data/receiverDeployment?id=3454
d <- 'SG-3214BBBK5757'



# get pulse summary from det_pulse_counts
query <- 'select
          ant,
          [count],
          tsBegin,
          receiverID,
          a.batchID,
          hourBin
          from det_pulse_counts a with (nolock)
          left join det_batches b with (nolock) on b.batchID = a.batchID
          left join sensors_hash_keys c with (nolock) on c.id = b.motusDeviceID
          where receiverID = ?'

pulse_counts <- dbGetQuery(db, query, params = d) %>% 
  mutate(dtBegin = as.POSIXct(tsBegin, tz = 'UTC', origin = '1970-01-01')) %>% 
  filter(dtBegin > '2015-01-01') # filter out some obvious bad dates

pulse_counts_by_batch <- pulse_counts %>% 
  group_by(batchID) %>% 
  summarise(pulses = sum(count, na.rm = T))

pulse_counts_by_date <- pulse_counts %>% 
  group_by(date = lubridate::date(dtBegin)) %>% 
  summarise(pulses = sum(count, na.rm = T))



# get hit summary from det_batches
query <-  'select 
          batchID, 
          receiverID, 
          numHits, 
          tsBegin 
          from det_batches a with (nolock)
          left join sensors_hash_keys b on b.id = a.motusDeviceID
          where receiverID = ?'

batches_hits_by_batch <- dbGetQuery(db, query, params = d) %>% 
  mutate(dtBegin = as.POSIXct(tsBegin, tz = 'UTC', origin = '1970-01-01')) %>% 
  filter(dtBegin > '2015-01-01')

batches_hits_by_day <- batches_hits_by_batch %>% 
  group_by(date = lubridate::date(dtBegin)) %>% 
  summarise(hits = sum(numHits, na.rm = T))



# get hit summary from det_taghits_runs
query <- 'select 
          batch_id,
          n_hits,
          receiverID,
          min_ts,
          max_ts
          from det_taghits_runs a with (nolock)
          left join sensors_hash_keys b on b.id = a.device_id
          where receiverID = ?'

runs_hits <- dbGetQuery(db, query, params = d) %>%
  mutate(min_dt = as.POSIXct(min_ts, tz = 'UTC', origin = '1970-01-01')) %>% 
  mutate(max_dt = as.POSIXct(max_ts, tz = 'UTC', origin = '1970-01-01')) %>% 
  filter(min_dt > '2015-01-01')

runs_hits_by_batch <- runs_hits %>% 
  group_by(batch_id) %>% 
  summarise(hits = sum(n_hits, na.rm = T))

runs_hits_by_day <- runs_hits %>% 
  group_by(date = lubridate::date(min_dt)) %>%
  summarise(hits = sum(n_hits, na.rm = T))


ggplot()

```
